from random import random

fruits = ['Acai', 'Apples', 'Apricots', 'Avocado', 'Ackee', 'Bananas', 'Bilberries', 'Blueberries', 'Blackberries', 'Cantaloupes', 'Cherimoya', 'Cherries', 'Clementines', 'Cranberries', 'Cucumbers', 'Currants', 'Dates', 'Dragonfruit', 'Durian', 'Eggplant', 'Elderberries', 'Figs', 'Gooseberries', 'Grapes', 'Grapefruit', 'Guava', 'Honeydew', 'Huckleberries', 'Jujubes', 'Kiwis', 'Durian', 'Kumquat', 'Lemons', 'Limes', 'Lychees', 'Mangos', 'Mangosteen', 'Mulberries', 'Muskmelon', 'Nectarines', 'Olives', 'Oranges', 'Papaya', 'Peaches', 'Pears', 'Peppers', 'Persimmon', 'Pineapple', 'Plums', 'Pluot', 'Pomegranate', 'Quince', 'Rambuton', 'Raspberries', 'Starfruit', 'Sapadilla', 'Strawberries', 'Tamarind', 'Tangelo', 'Tangerines', 'Tomatoes', 'Watermelons', 'Zucchini']
colors =  ['Fossil', 'Mink', 'Pearl', 'Abalone', 'Harbor', 'Smoke', 'Steel', 'Stone', 'Iron', 'Rhino', 'Shadow', 'Ash', 'Anchor', 'Charcoal', 'Cedar', 'Cinnamon', 'Brunette', 'Mocha', 'Umber', 'Tortilla', 'Chocolate', 'Syrup', 'Gingerbread', 'Caramel', 'Walnut', 'Pecan', 'Wood', 'Hickory', 'Espresso', 'Peanut', 'Tawny', 'Coffee', 'Russet', 'Forest', 'Sage', 'Olive', 'Lime', 'Hunter', 'Jade', 'Artichoke', 'Fern', 'Jungle', 'Laurel', 'Moss', 'Mint', 'Pine', 'Tea', 'Army', 'Emerald', 'Kelly', 'Sacramento', 'Sea', 'Yale', 'Pigeon', 'Sky', 'Independence', 'Baby', 'Navy', 'Steel', 'Carolina', 'Turkish', 'Maybe', 'Cornflower', 'Olympic', 'Sapphire', 'Azure', 'Egyptian', 'Denim', 'Prussian', 'Space', 'Salmon', 'Scarlet', 'Barn', 'Imperial', 'Indian', 'Chili', 'Redwood', 'Raspberry', 'Ferrari', 'Persian', 'Carmine', 'Burgundy', 'Crimson', 'Sangria', 'Mahogany', 'Ruby', 'Ultra', 'Thulian', 'Magenta', 'Lavender', 'Creamy', 'Fuchsia', 'Carnation', 'Brick', 'Amaranth', 'Taffy', 'Lemonade', 'Flamingo', 'Gold', 'Goldenrod', 'Pumpkin', 'Fire', 'Ochre', 'Burnt', 'Dijon', 'Tangerine', 'Tiger', 'Honey', 'Carrot', 'Amber', 'Apricot', 'Bronze', 'Cider', 'Clay', 'Rust', 'Amber', 'Spice']
names = ['Liam', 'Emma', 'Noah', 'Olivia', 'William', 'Ava', 'James', 'Isabella', 'Logan', 'Sophia', 'Benjamin', 'Mia', 'Mason', 'Charlotte', 'Elijah', 'Amelia', 'Oliver', 'Evelyn', 'Jacob', 'Abigail', 'Lucas', 'Harper', 'Michael', 'Emily', 'Alexander', 'Elizabeth', 'Ethan', 'Avery', 'Daniel', 'Sofia', 'Matthew', 'Ella', 'Aiden', 'Madison', 'Henry', 'Scarlett', 'Joseph', 'Victoria', 'Jackson', 'Aria', 'Samuel', 'Grace', 'Sebastian', 'Chloe', 'David', 'Camila', 'Carter', 'Penelope', 'Wyatt', 'Riley', 'Jayden', 'Layla', 'John', 'Lillian', 'Owen', 'Nora', 'Dylan', 'Zoey', 'Luke', 'Mila', 'Gabriel', 'Aubrey', 'Anthony', 'Hannah', 'Isaac', 'Lily', 'Grayson', 'Addison', 'Jack', 'Eleanor', 'Julian', 'Natalie', 'Levi', 'Luna', 'Christopher', 'Savannah', 'Joshua', 'Brooklyn', 'Andrew', 'Leah', 'Lincoln', 'Zoe', 'Mateo', 'Stella', 'Ryan', 'Hazel', 'Jaxon', 'Ellie', 'Nathan', 'Paisley', 'Aaron', 'Audrey', 'Isaiah', 'Skylar', 'Thomas', 'Violet', 'Charles', 'Claire', 'Caleb', 'Bella']

def create_space_url():
	fruit = fruits[int(random() * len(fruits))]
	color = colors[int(random() * len(colors))]
	name = names[int(random() * len(names))]

	return '{}{}{}'.format(fruit, color, name)
