# Generated by Django 2.0.1 on 2019-04-14 02:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('col_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(verbose_name='url')),
                ('participants', models.IntegerField(default=0)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='spaces', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
