# Generated by Django 2.0.1 on 2019-04-14 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('col_auth', '0002_space'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='code',
            field=models.TextField(blank=True, verbose_name='code'),
        ),
    ]
