# Generated by Django 2.0.1 on 2019-04-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('col_auth', '0003_space_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='submission',
            field=models.TextField(blank=True, verbose_name='submission'),
        ),
    ]
