# Generated by Django 2.0.1 on 2019-04-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('col_auth', '0004_space_submission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_code', models.TextField(blank=True, verbose_name='submission_code')),
            ],
        ),
        migrations.RemoveField(
            model_name='space',
            name='submission',
        ),
        migrations.AddField(
            model_name='space',
            name='submission',
            field=models.ManyToManyField(blank=True, to='col_auth.Submission'),
        ),
    ]
